self-hosted-runner:
  # Labels of self-hosted runner in array of strings.
  labels:
    - generic-runner
paths:
  .github/workflows/trigger_jenkins.yml:
    ignore:
      - shellcheck reported issue in this script: SC2116:.+
      - shellcheck reported issue in this script: SC2086:.+ 
      - shellcheck reported issue in this script: SC2001:.+    