BASE_NAME=rhel9.6
BASE_IMAGE=registry.access.redhat.com/ubi9/ubi:9.6
ARTIFACTORY_URL=vault.habana.ai
SYNAPSE_VERSION=1.24.0
SYNAPSE_REVISION=1007
PT_VERSION=2.10.0
VLLM_GAUDI_COMMIT=v0.19.0
VLLM_PROJECT_COMMIT=v0.19.0
