name: Trigger Jenkins Tests
on:
    pull_request:
        types: [opened, reopened, edited, synchronize]

permissions:
    pull-requests: write
jobs:
  TriggerJenkinsTests:
    runs-on: ubuntu-latest
    steps:
        - name: Trigger Jenkins Tests
          run: |
            curl -XPOST -H "Content-Type: application/json" \
            "${{ secrets.WEBHOOK_URL }}" \
            -d '${{ toJson(github) }}'          